version: '3.8'
services:
  node-app: 
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=devlopment
      - MONGO_USER=root
      - MONGO_PASSWORD=123123
      - SESSION_SECRET=secret
    command: npm run dev
  # mongo:
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: 123123