version: '3.8'
services:
  node-app: 
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      -  mongo
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    # env_file:
    #   - ./.env

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123123
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
  mongo-db: